# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"

    web.vm.network "private_network", ip: "192.168.33.191"

    web.vm.provider :virtualbox do |vb|
      # Use VBoxManage to customize the VM. For example to change memory:
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    web.vm.provision "shell", path: "scripts/ansible_bootstrap.sh"
    web.vm.provision "shell", path: "scripts/web/provision.sh"
  end
  
  config.vm.define "db" do |db|
    db.vm.box = "nickcharlton/postgres"
    
    db.vm.network "private_network", ip: "192.168.33.190"
    
  end
  
end
